["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/atotto/clipboard"]
  sumVersion = "v0.1.4"
  ["github.com/atotto/clipboard".fetch]
    type = "git"
    url = "https://github.com/atotto/clipboard"
    rev = "e4aee1922c628e6966acd4207c408df132dc6fb5"
    sha256 = "0ycd8zkgsq9iil9svhlwvhcqwcd7vik73nf8rnyfnn10gpjx97k5"

["github.com/cpuguy83/go-md2man/v2"]
  sumVersion = "v2.0.0"
  ["github.com/cpuguy83/go-md2man/v2".fetch]
    type = "git"
    url = "https://github.com/cpuguy83/go-md2man"
    rev = "f79a8a8ca69da163eee19ab442bedad7a35bba5a"
    sha256 = "0r1f7v475dxxgzqci1mxfliwadcrk86ippflx9n411325l4g3ghv"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/facebookgo/ensure"]
  sumVersion = "v0.0.0-20200202191622-63f1cf65ac4c"
  ["github.com/facebookgo/ensure".fetch]
    type = "git"
    url = "https://github.com/facebookgo/ensure"
    rev = "63f1cf65ac4cf1f4bd7e93292149a456001b0e0b"
    sha256 = "05vi49g2967i5awcb1z69i2n5b5hwn06682kw90x81hbxlr0px36"

["github.com/facebookgo/stack"]
  sumVersion = "v0.0.0-20160209184415-751773369052"
  ["github.com/facebookgo/stack".fetch]
    type = "git"
    url = "https://github.com/facebookgo/stack"
    rev = "751773369052141c013c6e827a71e8f35c07879c"
    sha256 = "07yr05mz7h007ldpij90zjflwgixp148sbyrdlh1fj5bikr4p8m3"

["github.com/facebookgo/subset"]
  sumVersion = "v0.0.0-20200203212716-c811ad88dec4"
  ["github.com/facebookgo/subset".fetch]
    type = "git"
    url = "https://github.com/facebookgo/subset"
    rev = "c811ad88dec4edb3d7af0a88b34e6865d7460ba2"
    sha256 = "1sjczgmq26mgqvh7267saypnn4sfdjx467wsm1pgdhyss77mc650"

["github.com/facebookgo/symwalk"]
  sumVersion = "v0.0.0-20150726040526-42004b9f3222"
  ["github.com/facebookgo/symwalk".fetch]
    type = "git"
    url = "https://github.com/facebookgo/symwalk"
    rev = "42004b9f322246749dd73ad71008b1f3160c0052"
    sha256 = "13fjx9gl3fdvy2gjxjyycy85g3xxb2zjiigakbgk0g5mxkb6i7m6"

["github.com/facebookgo/testname"]
  sumVersion = "v0.0.0-20150612200628-5443337c3a12"
  ["github.com/facebookgo/testname".fetch]
    type = "git"
    url = "https://github.com/facebookgo/testname"
    rev = "5443337c3a12e7194a181eceb64fc4b14c964b9b"
    sha256 = "10cha2x7d2azz37lrlm0qnrfml0rp6f2r9fj4y2s4419ap7hsxl2"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/russross/blackfriday/v2"]
  sumVersion = "v2.0.1"
  ["github.com/russross/blackfriday/v2".fetch]
    type = "git"
    url = "https://github.com/russross/blackfriday"
    rev = "d3b5b032dc8e8927d31a5071b56e14c89f045135"
    sha256 = "0nlz7isdd4rgnwzs68499hlwicxz34j2k2a0b8jy0y7ycd2bcr5j"

["github.com/shurcooL/sanitized_anchor_name"]
  sumVersion = "v1.0.0"
  ["github.com/shurcooL/sanitized_anchor_name".fetch]
    type = "git"
    url = "https://github.com/shurcooL/sanitized_anchor_name"
    rev = "7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615"
    sha256 = "1gv9p2nr46z80dnfjsklc6zxbgk96349sdsxjz05f3z6wb6m5l8f"

["github.com/urfave/cli/v2"]
  sumVersion = "v2.3.0"
  ["github.com/urfave/cli/v2".fetch]
    type = "git"
    url = "https://github.com/urfave/cli"
    rev = "09ac54c2f97f4249282baf266c54a09fab1bef58"
    sha256 = "08pvn7gyfznni72xrxfh2x6xxa8ykr7l1ka278js8g8qkh71bj8l"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.3"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "bb4e33bf68bf89cad44d386192cbed201f35b241"
    sha256 = "0l2s7y180gkkvrmnw2xyfszz1m4kp92x2hz680c9vyklcbzsxrrx"
